import type { Movie } from "../../../types/movieType";

export const trendingMovies: Movie[] = [
    {
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },{
        id: "1",
        title: "Oppenheimer",
        year: 2023,
        genres: ["Drama", "History"],
        director: "Christopher Nolan",
        actors: "Cillian Murphy, Emily Blunt",
        plot: "The story of J. Robert Oppenheimer and the atomic bomb.",
        runtime: "3h",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
        bannerUrl: "/banners/oppenheimer.jpg",
        trailerUrl: "https://youtube.com",
    },
    {
        id: "2",
        title: "Dune: Part Two",
        year: 2024,
        genres: ["Sci-Fi", "Adventure"],
        director: "Denis Villeneuve",
        actors: "Timothée Chalamet, Zendaya",
        plot: "Paul Atreides unites with the Fremen.",
        runtime: "2h 45m",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5ODAyNzA4OV5BMl5BanBnXkFtZTcwNzYwNTIzNA@@._V1_SX300.jpg",
        bannerUrl: "/banners/dune2.jpg",
        trailerUrl: "https://youtube.com",
    },
];
